variable "project_id" {}
variable "region" {}
variable "domain" {}
variable "bucket_names" {}
variable "upload_bucket" {}
variable "init_bucket" {}
variable "processed_chunk_file_bucket" {}
variable "audio_processed_chunk_bucket" {}
variable "video_to_audio_bucket" {}
